-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN "searchCenters" JSONB;
ALTER TABLE "Campaign" ADD COLUMN "gridRadiusMeters" INTEGER NOT NULL DEFAULT 2000;
ALTER TABLE "Campaign" ADD COLUMN "gridSpacingMeters" INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE "Campaign" ADD COLUMN "cellsPerRun" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Campaign" ADD COLUMN "rotateQueries" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Campaign" ADD COLUMN "searchQueryHistory" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
